export interface IFarmacia {
    Id: number;  
    RazaoSocial: string;  
    NomeFantasia: string;  
    Cnpj: string;  
    InscricaoEstadual: string;  
    InscricaoMunicipal: string;   
    RegimeTributario: number; 
    DDD: string; 
    Telefone: string;
    Celular: string;  
    Email: string;  
    WhatsApp: string;
    Cep: string;  
    Logradouro: string;  
    Numero: string;  
    Complemento: string;  
    CidadeId: number;  
    EstadoId: number;  
    BairroId: number;   
    NomeFarmaceutico: string;  
    CRF: number;  
    CpfRespSNGPC: string;  
    UsuarioSNGPC: string;   
    SenhaSNGPC: string;  
    Ativo: boolean; 
    LicencaFunc: string;  
    AutoridadeSanitaria: string;   
    LicencaMapa: string;   
    FornecedorInternoId: number;
}

export let Farmacia: IFarmacia = {
    Id: 0,
    RazaoSocial: "",
    NomeFantasia: "",
    Cnpj: "",
    InscricaoEstadual: "",
    InscricaoMunicipal: "",
    RegimeTributario: 0,
    DDD: "",
    Telefone: "",
    Celular: "",
    Email: "",
    WhatsApp: "",
    Cep: "",
    Logradouro: "",
    Numero: "",
    Complemento: "",
    CidadeId: 0,
    EstadoId: 0,
    BairroId: 0,
    NomeFarmaceutico: "",
    CRF: 0,
    CpfRespSNGPC: "",
    UsuarioSNGPC: "",
    SenhaSNGPC: "",
    Ativo: true,
    LicencaFunc: "",
    AutoridadeSanitaria: "",
    LicencaMapa: "",
    FornecedorInternoId: 0
}