export let prescritor = {
    id: 0,
    bairroId: null,
    cidadeId: null,
    estadoId: null,
    nome: "",
    cep: "",
    data_Nascimento: null,
    endereco: "",
    numero: "",
    complemento: "",
    cpfCnpj: "",
    ddd: "",
    dddCelular: "",
    telefone: "",
    celular: "",
    secretaria: "",
    nomeRotulo: "",
    ativo: true,
    genero: -1,
    tipoCr: -1,
    crmNumero: "",
    crmEstado: "",
    crmTipo: "",
    email: "",
    aniversario: "",
    enderecoRes: "",
    numeroRes: "",
    cepRes: "",
    dddRes: "",
    telefoneRes: "",
    proximidade: "",
    visitadorId: null,
    observacaoVenda: "",
    cedh: false,
    registroMapa: "",
    especialidadePrescritores:[] as any
};