export interface IItemsCompra {
    id: number,
    contaId: number,
    integracaoId: number,
    grupoId: number,
    laboratorioId: number,
    produtoId: number,
    comprar: boolean,
    curva: string,
    encomenda: boolean,
    estoque: number,
    estoqueMaximo: number,
    estoqueMinimo: number,
    comprasId: number,
    quantidadeCompra: number,
    quantidadeVendida: number,
    quantidadeTotal: number,
    valorTotal: number,
    valorUnitario: number,
    valorVendido: number,
    selecionadoGerar: string,
    consumoDiario: number,
    siglaUnidade: string,
    quantidadeCompraMaxima: number,
    fornecedorId: number,
    nomeFornecedor: string,
    descricao: string,
    nomeLaboratorio: string,
    codigoCas: string,
    codigoDcb: string,
    codigoBarra: string,
    codigoGrupo: string,
    codigoProduto: string
}



