import { IFormaFarmaceuticaEnsaios } from "./IFormaFarmaceuticaEnsaios"
import { IFormaFarmaceuticaMargens } from "./IFormaFarmaceuticaMargens"

export interface IFormaFarmaceutica {
    id: number,
    descricao: string,
    inativo: boolean,
    tipo: number,
    selecionaQuantidadeSugerida: boolean,
    multiplicaComposicao: boolean,
    homeopatiaLiquida: boolean,
    deduzirQuantidadeVeiculo: boolean,
    calculoEmbalagemForma: number | null,
    converteVolumeEmbalagem: boolean,
    uso: string,
    tipoUso: number,
    popForma: string,
    imprimirCamposAnalise: boolean,
    selecionarVolumeAutomatico: boolean,
    validade: number,
    mlGotas: number,
    imprimirUnidadeMedidaNoRotulo: boolean,
    fatorPerdaProduto: number,
    ativaFatorPerdaQsp: boolean,
    manipuladorId: number | null,
    quantidadeFormulasHora: number,
    descricaoRotulo: string,
    quantidadeQspMinimo: number,
    produtoVeiculoId: number | null,
    grupoVeiculoId: number | null,
    ativaPesagemMonitorada: boolean,
    calcularDensidade: boolean,
    valorMinimo: number,
    custoAdicional: number,
    ncmId: number | null,
    codigoLaboratorioLp: string,
    codigoFuncionarioManipulacao: number,
    codigoFormaReceituario: number,
    codigoFilialProducao: number,
    aliquotaIva: number,
    imagem: string | ArrayBuffer | null,
    imagemByte: string,
    formaFarmaceuticaMargens: IFormaFarmaceuticaMargens[],
    formaFarmaceuticaEnsaios: IFormaFarmaceuticaEnsaios[]
}