import Flat from "../assets/img/bench.png"

export const namesItemsMenu = [
  {img: Flat, titulo:"Administradora de Cartão"},
  {img: Flat, titulo:"Bairro"},
  {img: Flat, titulo:"Banco"},
  {img: Flat, titulo:"Bula"},
  {img: Flat, titulo:"Cidade"},
  {img: Flat, titulo:"Classe"},
  {img: Flat, titulo:"Conta Corrente"},
  {img: Flat, titulo:"Dcb"},
  {img: Flat, titulo:"Dci"},
  {img: Flat, titulo:"Ensaio"},
  {img: Flat, titulo:"Especialidade"},
  {img: Flat, titulo:"Especificação Cápsula"},
  {img: Flat, titulo:"Etapa"},
  {img: Flat, titulo:"Farmacopéia"},
  {img: Flat, titulo:"Forma de Pagamento"},
  {img: Flat, titulo:"Fornecedor"},
  {img: Flat, titulo:"Funcionário Laboratório"},
  // {img: Flat, titulo:"Grupo"},
  {img: Flat, titulo:"Laboratorio"},
  {img: Flat, titulo:"Máquina Pós"},
  {img: Flat, titulo:"Mensagens Padrão"},
  {img: Flat, titulo:"Método"},
  {img: Flat, titulo:"Motivo"},
  {img: Flat, titulo:"Natureza de Operação"},
  {img: Flat, titulo:"Nbm"},
  // {img: Flat, titulo:"Ncm"},
  {img: Flat, titulo:"País"},
  {img: Flat, titulo:"Parametro"},
  {img: Flat, titulo:"Pbm"},
  {img: Flat, titulo:"Portador"},
  {img: Flat, titulo:"Pós Adquirente"},
  {img: Flat, titulo:"Posologia"},
  {img: Flat, titulo:"Principio Ativo"},
  // {img: Flat, titulo:"Produto"},
  {img: Flat, titulo:"Tipo Contato"},
  {img: Flat, titulo:"Tipo Justificativa"},
  {img: Flat, titulo:"Tributo"},
  {img: Flat, titulo:"Transportador"},
  {img: Flat, titulo:"Etapa"},
  {img: Flat, titulo:"Máquina Pós"},
];